### ISSUE TITLE
Could MettaOS fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [metta-systems/metta#3]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by berkus** [comment]
The current build should fit on a floppy just fine. There are even some fd0 images that are made for just that, an 1.44Mb floppy.

**Comment by informer2016** [comment]
@berkus Thank you very much for reply! Please tell, why your latest official release (Metta-R925.iso) weights 9.8 MB _(significantly larger than 1.44 MB)_ - is it because no compression is used? Also, it seems the floppies have been removed at R840 - https://github.com/metta-systems/metta/commit/c48cca18edf71549ca3c6107b541f0de4c496f52 I'm just trying to clarify the technical possibility of a floppy before trying to build by myself 😉

**Comment by berkus** [comment]
The .iso files are for CD-emulation, there should be a .fd0 image that fits on a floppy.

I'm not sure why I removed fd0 support in R840 - probably because I never used it myself.

**Comment by informer2016** [comment]
@berkus Sadly there aren't many people who are interested both in coreboot BIOS and hobby OS, so I can understand you :wink:  But I will be checking MettaOS from time to time just in case you'd restore .fd0

**Comment by informer2016** [comment]
@berkus hope this could be re-opened one day...

**Comment by berkus** [comment]
You can build fd0 file yourself, just look at the script that generated it in the git history.
